spring:
  application.name: boot-rest
  jackson.serialization.write-dates-as-timestamps: false
  data.elasticsearch:
    cluster-name: ${spring.application.name}
    properties:
      node.name: Boot REST
      discovery.zen.ping.multicast.enabled: false

server.port: 8888

management:
  port: 8889
  context-path: /manage

security:
  basic.path: ${management.context-path}/**
  user:
    name: admin
    password: secret

logging.level.net.robi42.boot: DEBUG

web-client.connection-pool:
  max-total: 100
  default-max-per-route: 20
