spring.application.name: boot-rest
server.port: 8888
management.contextPath: /admin

admin:
  username: admin
  password: secret

elasticsearch.clusterName: boot-rest-cluster

---

spring:
  profiles: dev
  thymeleaf.cache: false
