spring.application.name: boot-rest
server.port: 8888
management.contextPath: /admin

admin:
  username: admin
  password: secret

webClient.connectionPool:
  maxTotal: 100
  defaultMaxPerRoute: 20

---

spring:
  profiles: dev
  thymeleaf.cache: false
